### ISSUE TITLE
graph-prototype: Implement genral sub-graph handling

### ISSUE THREAD

**Issue by ivan-cukic** [fair-acc/graph-prototype#116]
We have a demo of how to create a node that contains a scheduler with an arbitrary graph inside. We also need another type of a sub-graph - which exposes its nodes to the parent graph, that is, to the scheduler of the parent graph.

We need to discuss how to handle this - should a graph be a collection of nodes, graphs, schedulers, or should be be able to model graph and schedulers as nodes.

**Comment by wirew0rm** [comment]
closed in favor of preexisting #82
