### ISSUE TITLE
Enhancing Parameter Validation & Feedback in GNU Radio Blocks

### ISSUE THREAD

**Issue by drslebedev** [fair-acc/graph-prototype#146]
This issue is meant for a discussion and opinion exchange.

For the moment one already has 3 NTTP tags for `node` class: `BlockingIO`, `PerformDecimationInterpolation`, `PerformStride`.

These flags are used to enable/disable certain functionality for `node` class using `if constexpr` and thus without sacrificing performance.

The problem is that node parameters `numerator`, `denominator` and `stride` can be changed during runtime which can cause inconsistency. For example, block is not declared with `PerformDecimationInterpolation` tag but `numerator` or `denominator` are not 1. 

The current implementation just throws `std::runtime_error` for such inconsistencies. 
But probably there is a better choice: write a warning to the user, reject all new incompatible settings etc.

Please fill free to add your opinion in the comments below.

**Comment by RalphSteinhagen** [comment]
@mormj, @marcusmueller, and @dkozel we've been thinking about something that might be worth exploring in one of our future GNU Radio Architecture working group meetings. While it's not a pressing issue, it has caught my attention as something we can improve upon for the future of GR.

We currently don't have a feature for validating block settings before they're applied in GR 3.x, do we? I seem to recall us having a couple of chats about this or something similar in the past.

The idea I'd like to bring to the table is about refining the process of validating new parameter sets before they're accepted and applied by a GNU Radio block. Additionally, enhancing the way we communicate to the user - clearly letting them know whether their settings have been successfully implemented, and if not, explaining why.

If any relevant resources or documents spring to mind that could shed more light on this, it'd be great if you could share them here. As always, I value your insights. Thanks in advance!
