### ISSUE TITLE
[5SP] GR: Add API for Scheduler and Graph introspection

### ISSUE THREAD

**Issue by ivan-cukic** [fair-acc/graph-prototype#238]
Expose the API to access the graph topology:

 - Blocks traversal in a graph
 - Nested blocks traversal in a block (for sub-grapph-as-a-block node)
 - Connections traversal in a graph and nested blocks
 - Accessing blocks via unique identifiers
   (identifier, or for nested blocks parent_identifier/.../block_identifier)
 - Removing added blocks
 - Replacing blocks

Related: https://github.com/fair-acc/graph-prototype/issues/115

**Comment by RalphSteinhagen** [comment]
N.B. closed as this is merged with issue https://github.com/fair-acc/graph-prototype/issues/82
